// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blob.proto

package monohub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlobRequest struct {
	Sha                  string   `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobRequest) Reset()         { *m = BlobRequest{} }
func (m *BlobRequest) String() string { return proto.CompactTextString(m) }
func (*BlobRequest) ProtoMessage()    {}
func (*BlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6903d1e8a20272e8, []int{0}
}

func (m *BlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobRequest.Unmarshal(m, b)
}
func (m *BlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobRequest.Marshal(b, m, deterministic)
}
func (m *BlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobRequest.Merge(m, src)
}
func (m *BlobRequest) XXX_Size() int {
	return xxx_messageInfo_BlobRequest.Size(m)
}
func (m *BlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlobRequest proto.InternalMessageInfo

func (m *BlobRequest) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type BlobResponse struct {
	Sha                  string   `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Encoding             string   `protobuf:"bytes,3,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlobResponse) Reset()         { *m = BlobResponse{} }
func (m *BlobResponse) String() string { return proto.CompactTextString(m) }
func (*BlobResponse) ProtoMessage()    {}
func (*BlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6903d1e8a20272e8, []int{1}
}

func (m *BlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlobResponse.Unmarshal(m, b)
}
func (m *BlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlobResponse.Marshal(b, m, deterministic)
}
func (m *BlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobResponse.Merge(m, src)
}
func (m *BlobResponse) XXX_Size() int {
	return xxx_messageInfo_BlobResponse.Size(m)
}
func (m *BlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlobResponse proto.InternalMessageInfo

func (m *BlobResponse) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *BlobResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *BlobResponse) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *BlobResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *BlobResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*BlobRequest)(nil), "monohub.BlobRequest")
	proto.RegisterType((*BlobResponse)(nil), "monohub.BlobResponse")
}

func init() { proto.RegisterFile("blob.proto", fileDescriptor_6903d1e8a20272e8) }

var fileDescriptor_6903d1e8a20272e8 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xc9, 0x4f,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xcd, 0xcf, 0xcb, 0xcf, 0x28, 0x4d, 0x52,
	0x92, 0xe7, 0xe2, 0x76, 0xca, 0xc9, 0x4f, 0x0a, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe0, 0x62, 0x2e, 0xce, 0x48, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x6a,
	0xb8, 0x78, 0x20, 0x0a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x31, 0x55, 0x08, 0x49, 0x70, 0xb1,
	0x27, 0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x48, 0x30, 0x81, 0x45, 0x61, 0x5c, 0x21, 0x29, 0x2e,
	0x8e, 0xd4, 0xbc, 0xe4, 0xfc, 0x94, 0xcc, 0xbc, 0x74, 0x09, 0x66, 0xb0, 0x14, 0x9c, 0x0f, 0x32,
	0xa7, 0xb4, 0x28, 0x47, 0x82, 0x05, 0x62, 0x4e, 0x69, 0x51, 0x8e, 0x90, 0x10, 0x17, 0x4b, 0x71,
	0x66, 0x55, 0xaa, 0x04, 0xab, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x98, 0x9d, 0xc4, 0x06, 0x76, 0xae,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x01, 0xcc, 0x26, 0xbc, 0x00, 0x00, 0x00,
}
