// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commit.proto

package monohub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Parent struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parent) Reset()         { *m = Parent{} }
func (m *Parent) String() string { return proto.CompactTextString(m) }
func (*Parent) ProtoMessage()    {}
func (*Parent) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{0}
}

func (m *Parent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent.Unmarshal(m, b)
}
func (m *Parent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent.Marshal(b, m, deterministic)
}
func (m *Parent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent.Merge(m, src)
}
func (m *Parent) XXX_Size() int {
	return xxx_messageInfo_Parent.Size(m)
}
func (m *Parent) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent.DiscardUnknown(m)
}

var xxx_messageInfo_Parent proto.InternalMessageInfo

func (m *Parent) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Parent) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type Stats struct {
	Additions            int64    `protobuf:"varint,1,opt,name=additions,proto3" json:"additions,omitempty"`
	Deletions            int64    `protobuf:"varint,2,opt,name=deletions,proto3" json:"deletions,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{1}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetAdditions() int64 {
	if m != nil {
		return m.Additions
	}
	return 0
}

func (m *Stats) GetDeletions() int64 {
	if m != nil {
		return m.Deletions
	}
	return 0
}

func (m *Stats) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Author struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{2}
}

func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Author) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Author) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Author) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Tree struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tree) Reset()         { *m = Tree{} }
func (m *Tree) String() string { return proto.CompactTextString(m) }
func (*Tree) ProtoMessage()    {}
func (*Tree) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{3}
}

func (m *Tree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tree.Unmarshal(m, b)
}
func (m *Tree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tree.Marshal(b, m, deterministic)
}
func (m *Tree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tree.Merge(m, src)
}
func (m *Tree) XXX_Size() int {
	return xxx_messageInfo_Tree.Size(m)
}
func (m *Tree) XXX_DiscardUnknown() {
	xxx_messageInfo_Tree.DiscardUnknown(m)
}

var xxx_messageInfo_Tree proto.InternalMessageInfo

func (m *Tree) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Tree) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type Commit struct {
	Committer            *Author              `protobuf:"bytes,2,opt,name=committer,proto3" json:"committer,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Tree                 *Tree                `protobuf:"bytes,4,opt,name=tree,proto3" json:"tree,omitempty"`
	Author               *Author              `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{4}
}

func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetCommitter() *Author {
	if m != nil {
		return m.Committer
	}
	return nil
}

func (m *Commit) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Commit) GetTree() *Tree {
	if m != nil {
		return m.Tree
	}
	return nil
}

func (m *Commit) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Commit) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type File struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Additions            int64    `protobuf:"varint,2,opt,name=additions,proto3" json:"additions,omitempty"`
	Changes              int64    `protobuf:"varint,3,opt,name=changes,proto3" json:"changes,omitempty"`
	Deletions            int64    `protobuf:"varint,4,opt,name=deletions,proto3" json:"deletions,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	BlobUrl              string   `protobuf:"bytes,6,opt,name=blob_url,json=blobUrl,proto3" json:"blob_url,omitempty"`
	Patch                string   `protobuf:"bytes,7,opt,name=patch,proto3" json:"patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{5}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetAdditions() int64 {
	if m != nil {
		return m.Additions
	}
	return 0
}

func (m *File) GetChanges() int64 {
	if m != nil {
		return m.Changes
	}
	return 0
}

func (m *File) GetDeletions() int64 {
	if m != nil {
		return m.Deletions
	}
	return 0
}

func (m *File) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *File) GetBlobUrl() string {
	if m != nil {
		return m.BlobUrl
	}
	return ""
}

func (m *File) GetPatch() string {
	if m != nil {
		return m.Patch
	}
	return ""
}

type CommitRequest struct {
	Sha                  string   `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{6}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type CommitResponse struct {
	Sha                  string    `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	Author               *Author   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Files                []*File   `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	Stats                *Stats    `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	Parents              []*Parent `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	Commit               *Commit   `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommitResponse) Reset()         { *m = CommitResponse{} }
func (m *CommitResponse) String() string { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()    {}
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db7163399a465f48, []int{7}
}

func (m *CommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResponse.Unmarshal(m, b)
}
func (m *CommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResponse.Marshal(b, m, deterministic)
}
func (m *CommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResponse.Merge(m, src)
}
func (m *CommitResponse) XXX_Size() int {
	return xxx_messageInfo_CommitResponse.Size(m)
}
func (m *CommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResponse proto.InternalMessageInfo

func (m *CommitResponse) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *CommitResponse) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *CommitResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *CommitResponse) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *CommitResponse) GetParents() []*Parent {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *CommitResponse) GetCommit() *Commit {
	if m != nil {
		return m.Commit
	}
	return nil
}

func init() {
	proto.RegisterType((*Parent)(nil), "monohub.Parent")
	proto.RegisterType((*Stats)(nil), "monohub.Stats")
	proto.RegisterType((*Author)(nil), "monohub.Author")
	proto.RegisterType((*Tree)(nil), "monohub.Tree")
	proto.RegisterType((*Commit)(nil), "monohub.Commit")
	proto.RegisterType((*File)(nil), "monohub.File")
	proto.RegisterType((*CommitRequest)(nil), "monohub.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "monohub.CommitResponse")
}

func init() { proto.RegisterFile("commit.proto", fileDescriptor_db7163399a465f48) }

var fileDescriptor_db7163399a465f48 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x8a, 0xd4, 0x30,
	0x14, 0xc6, 0x69, 0xa7, 0xd3, 0x6e, 0xcf, 0xba, 0xa3, 0x04, 0x91, 0x3a, 0x08, 0xba, 0x55, 0xf0,
	0x0f, 0xda, 0x85, 0xf5, 0x09, 0x44, 0xf0, 0x5a, 0xe2, 0x0a, 0x7a, 0x25, 0xe9, 0xf4, 0x6c, 0x1b,
	0x48, 0x9b, 0xda, 0xa4, 0x0f, 0xe8, 0x03, 0xf8, 0x22, 0x3e, 0x85, 0xe4, 0x24, 0x9d, 0x71, 0x56,
	0x91, 0xbd, 0xeb, 0x39, 0xdf, 0x37, 0xc9, 0x39, 0xdf, 0x6f, 0x02, 0x77, 0x76, 0xba, 0xef, 0xa5,
	0xad, 0xc6, 0x49, 0x5b, 0xcd, 0xb2, 0x5e, 0x0f, 0xba, 0x9b, 0xeb, 0xed, 0xe3, 0x56, 0xeb, 0x56,
	0xe1, 0x05, 0xb5, 0xeb, 0xf9, 0xfa, 0xc2, 0xca, 0x1e, 0x8d, 0x15, 0xfd, 0xe8, 0x9d, 0xe5, 0x6b,
	0x48, 0x3f, 0x8a, 0x09, 0x07, 0xcb, 0xee, 0xc1, 0x6a, 0x9e, 0x54, 0x11, 0x3d, 0x89, 0x5e, 0xe4,
	0xdc, 0x7d, 0xba, 0x8e, 0xe9, 0x44, 0x11, 0xfb, 0x8e, 0xe9, 0x44, 0xf9, 0x15, 0xd6, 0x9f, 0xac,
	0xb0, 0x86, 0x3d, 0x82, 0x5c, 0x34, 0x8d, 0xb4, 0x52, 0x0f, 0x86, 0x7e, 0xb2, 0xe2, 0x87, 0x86,
	0x53, 0x1b, 0x54, 0xe8, 0xd5, 0xd8, 0xab, 0xfb, 0x06, 0xbb, 0x0f, 0x6b, 0xab, 0xad, 0x50, 0xc5,
	0x8a, 0x14, 0x5f, 0x94, 0x5f, 0x20, 0x7d, 0x37, 0xdb, 0x4e, 0x4f, 0x6c, 0x03, 0xb1, 0x6c, 0xc2,
	0xa1, 0xb1, 0x6c, 0x9c, 0x5f, 0xe9, 0x56, 0x0e, 0x61, 0x10, 0x5f, 0x30, 0x06, 0xc9, 0x20, 0x7a,
	0xa4, 0x43, 0x72, 0x4e, 0xdf, 0xce, 0x89, 0xbd, 0x90, 0xaa, 0x48, 0xbc, 0x93, 0x8a, 0xf2, 0x15,
	0x24, 0x57, 0x13, 0xe2, 0xad, 0x16, 0xfc, 0x19, 0x41, 0xfa, 0x9e, 0x92, 0x64, 0x6f, 0x20, 0xf7,
	0x99, 0x5a, 0x9c, 0xc8, 0x72, 0x7a, 0x79, 0xb7, 0x0a, 0xb9, 0x56, 0x7e, 0x54, 0x7e, 0x70, 0xb0,
	0x02, 0xb2, 0x1e, 0x8d, 0x11, 0xed, 0x32, 0xd2, 0x52, 0xb2, 0x73, 0x48, 0xec, 0x84, 0x48, 0x43,
	0x9d, 0x5e, 0x9e, 0xed, 0xcf, 0x70, 0x43, 0x71, 0x92, 0xd8, 0x73, 0x48, 0x05, 0x9d, 0x58, 0xac,
	0xff, 0x7d, 0x51, 0x90, 0x59, 0x05, 0x49, 0x23, 0x2c, 0x16, 0x29, 0xd9, 0xb6, 0x95, 0xc7, 0x5b,
	0x2d, 0x78, 0xab, 0xab, 0x05, 0x2f, 0x27, 0x5f, 0xf9, 0x23, 0x82, 0xe4, 0x83, 0x54, 0xc8, 0xb6,
	0x70, 0x72, 0x2d, 0x15, 0x52, 0x64, 0x3e, 0x81, 0x7d, 0x7d, 0x0c, 0x33, 0xbe, 0x09, 0xb3, 0x80,
	0x6c, 0xd7, 0x89, 0xa1, 0x45, 0x13, 0x80, 0x2d, 0xe5, 0x31, 0xe6, 0xe4, 0x26, 0xe6, 0x07, 0x90,
	0x1a, 0x2b, 0xec, 0x6c, 0x68, 0xa7, 0x9c, 0x87, 0x8a, 0x3d, 0x84, 0x93, 0x5a, 0xe9, 0xfa, 0x9b,
	0x63, 0x91, 0xfa, 0xa4, 0x5c, 0xfd, 0x79, 0x52, 0x8e, 0xdf, 0x28, 0xec, 0xae, 0x2b, 0x32, 0xcf,
	0x8f, 0x8a, 0xf2, 0x1c, 0xce, 0x3c, 0x12, 0x8e, 0xdf, 0x67, 0x34, 0x76, 0xc1, 0x16, 0x1d, 0xb0,
	0xfd, 0x8a, 0x60, 0xb3, 0x78, 0xcc, 0xa8, 0x07, 0x83, 0x7f, 0x9b, 0xfe, 0x08, 0x39, 0xfe, 0x7f,
	0xc8, 0x4f, 0x61, 0xed, 0xb2, 0x71, 0xfb, 0xae, 0x8e, 0x88, 0xb9, 0x24, 0xb9, 0xd7, 0xd8, 0x33,
	0x58, 0xbb, 0x85, 0x4c, 0xc0, 0xba, 0xd9, 0x9b, 0xe8, 0x81, 0x70, 0x2f, 0xb2, 0x97, 0x90, 0x8d,
	0xf4, 0xbc, 0x5c, 0x0a, 0xab, 0xa3, 0x4b, 0xfd, 0xb3, 0xe3, 0x8b, 0xee, 0xc6, 0xf3, 0xff, 0xa6,
	0x00, 0xf7, 0xe0, 0x0c, 0x9b, 0x05, 0xb9, 0x4e, 0x89, 0xf6, 0xdb, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x97, 0xec, 0xad, 0xea, 0xf3, 0x03, 0x00, 0x00,
}
