// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monohub.proto

package monohub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{0}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingReply struct {
	Version              string   `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReply) Reset()         { *m = PingReply{} }
func (m *PingReply) String() string { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()    {}
func (*PingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{1}
}
func (m *PingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReply.Unmarshal(m, b)
}
func (m *PingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReply.Marshal(b, m, deterministic)
}
func (dst *PingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReply.Merge(dst, src)
}
func (m *PingReply) XXX_Size() int {
	return xxx_messageInfo_PingReply.Size(m)
}
func (m *PingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReply.DiscardUnknown(m)
}

var xxx_messageInfo_PingReply proto.InternalMessageInfo

func (m *PingReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Parent struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parent) Reset()         { *m = Parent{} }
func (m *Parent) String() string { return proto.CompactTextString(m) }
func (*Parent) ProtoMessage()    {}
func (*Parent) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{2}
}
func (m *Parent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parent.Unmarshal(m, b)
}
func (m *Parent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parent.Marshal(b, m, deterministic)
}
func (dst *Parent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parent.Merge(dst, src)
}
func (m *Parent) XXX_Size() int {
	return xxx_messageInfo_Parent.Size(m)
}
func (m *Parent) XXX_DiscardUnknown() {
	xxx_messageInfo_Parent.DiscardUnknown(m)
}

var xxx_messageInfo_Parent proto.InternalMessageInfo

func (m *Parent) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Parent) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type Stats struct {
	Additions            int32    `protobuf:"varint,1,opt,name=additions" json:"additions,omitempty"`
	Deletions            int32    `protobuf:"varint,2,opt,name=deletions" json:"deletions,omitempty"`
	Total                int32    `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{3}
}
func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (dst *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(dst, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetAdditions() int32 {
	if m != nil {
		return m.Additions
	}
	return 0
}

func (m *Stats) GetDeletions() int32 {
	if m != nil {
		return m.Deletions
	}
	return 0
}

func (m *Stats) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Author struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{4}
}
func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (dst *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(dst, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Author) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type File struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Additions            int32    `protobuf:"varint,2,opt,name=additions" json:"additions,omitempty"`
	Changes              int32    `protobuf:"varint,3,opt,name=changes" json:"changes,omitempty"`
	Deletions            int32    `protobuf:"varint,4,opt,name=deletions" json:"deletions,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
	BlobUrl              string   `protobuf:"bytes,6,opt,name=blob_url,json=blobUrl" json:"blob_url,omitempty"`
	Patch                []byte   `protobuf:"bytes,7,opt,name=patch,proto3" json:"patch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{5}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *File) GetAdditions() int32 {
	if m != nil {
		return m.Additions
	}
	return 0
}

func (m *File) GetChanges() int32 {
	if m != nil {
		return m.Changes
	}
	return 0
}

func (m *File) GetDeletions() int32 {
	if m != nil {
		return m.Deletions
	}
	return 0
}

func (m *File) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *File) GetBlobUrl() string {
	if m != nil {
		return m.BlobUrl
	}
	return ""
}

func (m *File) GetPatch() []byte {
	if m != nil {
		return m.Patch
	}
	return nil
}

type CommitRequest struct {
	Sha                  string   `protobuf:"bytes,1,opt,name=sha" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{6}
}
func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (dst *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(dst, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type CommitResponse struct {
	Sha                  string    `protobuf:"bytes,1,opt,name=sha" json:"sha,omitempty"`
	Author               *Author   `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Files                []*File   `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
	Stats                *Stats    `protobuf:"bytes,4,opt,name=stats" json:"stats,omitempty"`
	Parents              []*Parent `protobuf:"bytes,5,rep,name=parents" json:"parents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommitResponse) Reset()         { *m = CommitResponse{} }
func (m *CommitResponse) String() string { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()    {}
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monohub_ac3be94c02d278be, []int{7}
}
func (m *CommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResponse.Unmarshal(m, b)
}
func (m *CommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResponse.Marshal(b, m, deterministic)
}
func (dst *CommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResponse.Merge(dst, src)
}
func (m *CommitResponse) XXX_Size() int {
	return xxx_messageInfo_CommitResponse.Size(m)
}
func (m *CommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResponse proto.InternalMessageInfo

func (m *CommitResponse) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *CommitResponse) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *CommitResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *CommitResponse) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *CommitResponse) GetParents() []*Parent {
	if m != nil {
		return m.Parents
	}
	return nil
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "monohub.PingRequest")
	proto.RegisterType((*PingReply)(nil), "monohub.PingReply")
	proto.RegisterType((*Parent)(nil), "monohub.Parent")
	proto.RegisterType((*Stats)(nil), "monohub.Stats")
	proto.RegisterType((*Author)(nil), "monohub.Author")
	proto.RegisterType((*File)(nil), "monohub.File")
	proto.RegisterType((*CommitRequest)(nil), "monohub.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "monohub.CommitResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonoHubClient is the client API for MonoHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonoHubClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Commits(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
}

type monoHubClient struct {
	cc *grpc.ClientConn
}

func NewMonoHubClient(cc *grpc.ClientConn) MonoHubClient {
	return &monoHubClient{cc}
}

func (c *monoHubClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/monohub.MonoHub/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monoHubClient) Commits(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, "/monohub.MonoHub/Commits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonoHubServer is the server API for MonoHub service.
type MonoHubServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Commits(context.Context, *CommitRequest) (*CommitResponse, error)
}

func RegisterMonoHubServer(s *grpc.Server, srv MonoHubServer) {
	s.RegisterService(&_MonoHub_serviceDesc, srv)
}

func _MonoHub_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoHubServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monohub.MonoHub/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoHubServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonoHub_Commits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonoHubServer).Commits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monohub.MonoHub/Commits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonoHubServer).Commits(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonoHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monohub.MonoHub",
	HandlerType: (*MonoHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MonoHub_Ping_Handler,
		},
		{
			MethodName: "Commits",
			Handler:    _MonoHub_Commits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monohub.proto",
}

func init() { proto.RegisterFile("monohub.proto", fileDescriptor_monohub_ac3be94c02d278be) }

var fileDescriptor_monohub_ac3be94c02d278be = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0x41, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0x92, 0x26, 0x69, 0x7f, 0x48, 0x19, 0x99, 0xd1, 0x10, 0xaa, 0x59, 0x0c, 0x01, 0x44,
	0x91, 0x50, 0x2b, 0xca, 0x09, 0x00, 0x09, 0xb1, 0x41, 0x8c, 0x8c, 0x58, 0xb0, 0x42, 0x4e, 0x63,
	0x12, 0x4b, 0xae, 0x1d, 0x62, 0x67, 0xa4, 0xd9, 0x72, 0x05, 0xf6, 0xdc, 0x65, 0xce, 0xc0, 0x15,
	0x38, 0xc8, 0xc8, 0x76, 0x92, 0xaa, 0xed, 0x2e, 0xef, 0xbf, 0xe7, 0xef, 0xff, 0x9e, 0x7f, 0x20,
	0xdd, 0x49, 0x21, 0xeb, 0xae, 0x58, 0x35, 0xad, 0xd4, 0x12, 0xc5, 0x3d, 0x5c, 0x5c, 0x56, 0x52,
	0x56, 0x9c, 0xae, 0x49, 0xc3, 0xd6, 0x44, 0x08, 0xa9, 0x89, 0x66, 0x52, 0x28, 0x27, 0xcb, 0x53,
	0x48, 0xae, 0x99, 0xa8, 0x30, 0xfd, 0xd5, 0x51, 0xa5, 0xf3, 0x17, 0x30, 0x73, 0xb0, 0xe1, 0xb7,
	0x28, 0x83, 0xf8, 0x86, 0xb6, 0x8a, 0x49, 0x91, 0x79, 0x57, 0xde, 0x72, 0x86, 0x07, 0x98, 0xbf,
	0x86, 0xe8, 0x9a, 0xb4, 0x54, 0x68, 0x74, 0x06, 0x41, 0xd7, 0xf2, 0x9e, 0x37, 0x9f, 0xa6, 0xa2,
	0x6a, 0x92, 0xf9, 0xae, 0xa2, 0x6a, 0x92, 0x7f, 0x87, 0xf0, 0xab, 0x26, 0x5a, 0xa1, 0x4b, 0x98,
	0x91, 0xb2, 0x64, 0xf6, 0x7e, 0x7b, 0x24, 0xc4, 0xfb, 0x82, 0x61, 0x4b, 0xca, 0xa9, 0x63, 0x7d,
	0xc7, 0x8e, 0x05, 0x74, 0x0e, 0xa1, 0x96, 0x9a, 0xf0, 0x2c, 0xb0, 0x8c, 0x03, 0xf9, 0x0a, 0xa2,
	0x77, 0x9d, 0xae, 0x65, 0x8b, 0xe6, 0xe0, 0xb3, 0xd2, 0x36, 0x0d, 0xb0, 0xcf, 0x4a, 0xa3, 0xe7,
	0xb2, 0x62, 0xa2, 0x1f, 0xc4, 0x81, 0xfc, 0xce, 0x83, 0xc9, 0x47, 0xc6, 0x29, 0x5a, 0xc0, 0xf4,
	0x27, 0xe3, 0x54, 0x90, 0x1d, 0xed, 0x87, 0x1f, 0xf1, 0xe1, 0x98, 0xfe, 0xf1, 0x98, 0x19, 0xc4,
	0xdb, 0x9a, 0x88, 0x8a, 0xaa, 0x7e, 0x94, 0x01, 0x1e, 0x1a, 0x98, 0x1c, 0x1b, 0xb8, 0x80, 0x48,
	0x69, 0xa2, 0x3b, 0x95, 0x85, 0xf6, 0xbe, 0x1e, 0xa1, 0x27, 0x30, 0x2d, 0xb8, 0x2c, 0x7e, 0x98,
	0x18, 0x23, 0x17, 0xb3, 0xc1, 0xdf, 0x5a, 0x6e, 0x3c, 0x34, 0x44, 0x6f, 0xeb, 0x2c, 0xbe, 0xf2,
	0x96, 0x0f, 0xb0, 0x03, 0xf9, 0x53, 0x48, 0x3f, 0xc8, 0xdd, 0x8e, 0xe9, 0xfe, 0xd1, 0x86, 0xc4,
	0xbd, 0x7d, 0xe2, 0x77, 0x1e, 0xcc, 0x07, 0x8d, 0x6a, 0xa4, 0x50, 0xf4, 0x54, 0x84, 0x5e, 0x42,
	0x44, 0x6c, 0x76, 0xd6, 0x63, 0xb2, 0x79, 0xb8, 0x1a, 0x36, 0xc8, 0x45, 0x8a, 0x7b, 0x1a, 0x3d,
	0x83, 0xd0, 0x64, 0x63, 0xfc, 0x06, 0xcb, 0x64, 0x93, 0x8e, 0x3a, 0x93, 0x24, 0x76, 0x1c, 0x7a,
	0x0e, 0xa1, 0x31, 0xe4, 0x8c, 0x27, 0x9b, 0xf9, 0x28, 0xb2, 0x4f, 0x8f, 0x1d, 0x89, 0x5e, 0x41,
	0xdc, 0xd8, 0xc5, 0x31, 0x29, 0x04, 0x07, 0x97, 0xba, 0x85, 0xc2, 0x03, 0xbf, 0xf9, 0xeb, 0x41,
	0xfc, 0x59, 0x0a, 0xf9, 0xa9, 0x2b, 0xd0, 0x7b, 0x98, 0x98, 0xb5, 0x44, 0xe7, 0x7b, 0xf5, 0x7e,
	0x69, 0x17, 0xe8, 0xa8, 0xda, 0xf0, 0xdb, 0xfc, 0xec, 0xf7, 0xbf, 0xff, 0x7f, 0x7c, 0x40, 0xd3,
	0xf5, 0xcd, 0x9b, 0x75, 0x63, 0xce, 0x7e, 0x81, 0xd8, 0x45, 0xa2, 0xd0, 0xc5, 0x78, 0xe0, 0x20,
	0xc8, 0xc5, 0xe3, 0x93, 0xba, 0x0b, 0x2f, 0x7f, 0x64, 0xbb, 0xa5, 0x28, 0x31, 0xdd, 0xb6, 0xae,
	0x4b, 0x11, 0xd9, 0x3f, 0xe8, 0xed, 0x7d, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0x9b, 0x7e, 0x50,
	0x79, 0x03, 0x00, 0x00,
}
