// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reference.proto

package monohub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReferenceRequest struct {
	Ref                  string   `protobuf:"bytes,1,opt,name=ref" json:"ref,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReferenceRequest) Reset()         { *m = ReferenceRequest{} }
func (m *ReferenceRequest) String() string { return proto.CompactTextString(m) }
func (*ReferenceRequest) ProtoMessage()    {}
func (*ReferenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_reference_928cccbef32ec0d6, []int{0}
}
func (m *ReferenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceRequest.Unmarshal(m, b)
}
func (m *ReferenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceRequest.Marshal(b, m, deterministic)
}
func (dst *ReferenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceRequest.Merge(dst, src)
}
func (m *ReferenceRequest) XXX_Size() int {
	return xxx_messageInfo_ReferenceRequest.Size(m)
}
func (m *ReferenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceRequest proto.InternalMessageInfo

func (m *ReferenceRequest) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

type RefObject struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefObject) Reset()         { *m = RefObject{} }
func (m *RefObject) String() string { return proto.CompactTextString(m) }
func (*RefObject) ProtoMessage()    {}
func (*RefObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_reference_928cccbef32ec0d6, []int{1}
}
func (m *RefObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefObject.Unmarshal(m, b)
}
func (m *RefObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefObject.Marshal(b, m, deterministic)
}
func (dst *RefObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefObject.Merge(dst, src)
}
func (m *RefObject) XXX_Size() int {
	return xxx_messageInfo_RefObject.Size(m)
}
func (m *RefObject) XXX_DiscardUnknown() {
	xxx_messageInfo_RefObject.DiscardUnknown(m)
}

var xxx_messageInfo_RefObject proto.InternalMessageInfo

func (m *RefObject) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RefObject) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type ReferenceResponse struct {
	Ref                  string       `protobuf:"bytes,1,opt,name=ref" json:"ref,omitempty"`
	NodeId               string       `protobuf:"bytes,2,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	Objects              []*RefObject `protobuf:"bytes,3,rep,name=objects" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReferenceResponse) Reset()         { *m = ReferenceResponse{} }
func (m *ReferenceResponse) String() string { return proto.CompactTextString(m) }
func (*ReferenceResponse) ProtoMessage()    {}
func (*ReferenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reference_928cccbef32ec0d6, []int{2}
}
func (m *ReferenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceResponse.Unmarshal(m, b)
}
func (m *ReferenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceResponse.Marshal(b, m, deterministic)
}
func (dst *ReferenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceResponse.Merge(dst, src)
}
func (m *ReferenceResponse) XXX_Size() int {
	return xxx_messageInfo_ReferenceResponse.Size(m)
}
func (m *ReferenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceResponse proto.InternalMessageInfo

func (m *ReferenceResponse) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *ReferenceResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ReferenceResponse) GetObjects() []*RefObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

func init() {
	proto.RegisterType((*ReferenceRequest)(nil), "monohub.ReferenceRequest")
	proto.RegisterType((*RefObject)(nil), "monohub.RefObject")
	proto.RegisterType((*ReferenceResponse)(nil), "monohub.ReferenceResponse")
}

func init() { proto.RegisterFile("reference.proto", fileDescriptor_reference_928cccbef32ec0d6) }

var fileDescriptor_reference_928cccbef32ec0d6 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4a, 0x4d, 0x4b,
	0x2d, 0x4a, 0xcd, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xcd, 0xcf,
	0xcb, 0xcf, 0x28, 0x4d, 0x52, 0x52, 0xe1, 0x12, 0x08, 0x82, 0xc9, 0x05, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0x17, 0xa5, 0xa6, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0x98, 0x4a, 0x86, 0x5c, 0x9c, 0x41, 0xa9, 0x69, 0xfe, 0x49, 0x59, 0xa9, 0xc9, 0x25, 0x42,
	0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x50, 0x79, 0x30, 0x1b, 0xa4, 0xa5, 0x38, 0x23, 0x51,
	0x82, 0x09, 0xa2, 0xa5, 0x38, 0x23, 0x51, 0x29, 0x87, 0x4b, 0x10, 0xc9, 0xe0, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x4c, 0x93, 0x85, 0xc4, 0xb9, 0xd8, 0xf3, 0xf2, 0x53, 0x52, 0xe3, 0x33, 0x53,
	0xa0, 0x9a, 0xd9, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x1d, 0x2e, 0xf6, 0x7c, 0xb0, 0x7d, 0xc5, 0x12,
	0xcc, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x42, 0x7a, 0x50, 0x37, 0xeb, 0xc1, 0x9d, 0x12, 0x04, 0x53,
	0x92, 0xc4, 0x06, 0xf6, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xed, 0x80, 0xc3, 0x0e, 0xe9,
	0x00, 0x00, 0x00,
}
