// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tags.proto

package monohub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TagRequest struct {
	Sha                  string   `protobuf:"bytes,1,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagRequest) Reset()         { *m = TagRequest{} }
func (m *TagRequest) String() string { return proto.CompactTextString(m) }
func (*TagRequest) ProtoMessage()    {}
func (*TagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d9cbcae1e528f6, []int{0}
}

func (m *TagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagRequest.Unmarshal(m, b)
}
func (m *TagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagRequest.Marshal(b, m, deterministic)
}
func (m *TagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagRequest.Merge(m, src)
}
func (m *TagRequest) XXX_Size() int {
	return xxx_messageInfo_TagRequest.Size(m)
}
func (m *TagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagRequest proto.InternalMessageInfo

func (m *TagRequest) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type Tagger struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tagger) Reset()         { *m = Tagger{} }
func (m *Tagger) String() string { return proto.CompactTextString(m) }
func (*Tagger) ProtoMessage()    {}
func (*Tagger) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d9cbcae1e528f6, []int{1}
}

func (m *Tagger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tagger.Unmarshal(m, b)
}
func (m *Tagger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tagger.Marshal(b, m, deterministic)
}
func (m *Tagger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tagger.Merge(m, src)
}
func (m *Tagger) XXX_Size() int {
	return xxx_messageInfo_Tagger.Size(m)
}
func (m *Tagger) XXX_DiscardUnknown() {
	xxx_messageInfo_Tagger.DiscardUnknown(m)
}

var xxx_messageInfo_Tagger proto.InternalMessageInfo

func (m *Tagger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Tagger) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type TagObject struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sha                  string   `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagObject) Reset()         { *m = TagObject{} }
func (m *TagObject) String() string { return proto.CompactTextString(m) }
func (*TagObject) ProtoMessage()    {}
func (*TagObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d9cbcae1e528f6, []int{2}
}

func (m *TagObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagObject.Unmarshal(m, b)
}
func (m *TagObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagObject.Marshal(b, m, deterministic)
}
func (m *TagObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagObject.Merge(m, src)
}
func (m *TagObject) XXX_Size() int {
	return xxx_messageInfo_TagObject.Size(m)
}
func (m *TagObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TagObject.DiscardUnknown(m)
}

var xxx_messageInfo_TagObject proto.InternalMessageInfo

func (m *TagObject) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TagObject) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

type TagResponse struct {
	Tag                  string     `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	NodeId               string     `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Object               *TagObject `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Sha                  string     `protobuf:"bytes,4,opt,name=sha,proto3" json:"sha,omitempty"`
	Message              string     `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Tagger               *Tagger    `protobuf:"bytes,6,opt,name=tagger,proto3" json:"tagger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TagResponse) Reset()         { *m = TagResponse{} }
func (m *TagResponse) String() string { return proto.CompactTextString(m) }
func (*TagResponse) ProtoMessage()    {}
func (*TagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d9cbcae1e528f6, []int{3}
}

func (m *TagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagResponse.Unmarshal(m, b)
}
func (m *TagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagResponse.Marshal(b, m, deterministic)
}
func (m *TagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagResponse.Merge(m, src)
}
func (m *TagResponse) XXX_Size() int {
	return xxx_messageInfo_TagResponse.Size(m)
}
func (m *TagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagResponse proto.InternalMessageInfo

func (m *TagResponse) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *TagResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *TagResponse) GetObject() *TagObject {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *TagResponse) GetSha() string {
	if m != nil {
		return m.Sha
	}
	return ""
}

func (m *TagResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TagResponse) GetTagger() *Tagger {
	if m != nil {
		return m.Tagger
	}
	return nil
}

func init() {
	proto.RegisterType((*TagRequest)(nil), "monohub.TagRequest")
	proto.RegisterType((*Tagger)(nil), "monohub.Tagger")
	proto.RegisterType((*TagObject)(nil), "monohub.TagObject")
	proto.RegisterType((*TagResponse)(nil), "monohub.TagResponse")
}

func init() { proto.RegisterFile("tags.proto", fileDescriptor_e7d9cbcae1e528f6) }

var fileDescriptor_e7d9cbcae1e528f6 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0x4d, 0x4b, 0xc4, 0x40,
	0x0c, 0xa5, 0xfb, 0x31, 0x65, 0xb3, 0x07, 0x25, 0x08, 0xce, 0x49, 0x96, 0x5e, 0x5c, 0x3c, 0x14,
	0x5c, 0x7f, 0x85, 0x27, 0xa1, 0xf4, 0x2e, 0xa9, 0x0d, 0xd9, 0x15, 0xdb, 0xa9, 0x9d, 0xe9, 0xc1,
	0x9f, 0xe6, 0xbf, 0x93, 0xc6, 0x99, 0xea, 0xed, 0xbd, 0x24, 0x2f, 0xef, 0x25, 0x00, 0x81, 0xc4,
	0x97, 0xc3, 0xe8, 0x82, 0xc3, 0xbc, 0x73, 0xbd, 0x3b, 0x4f, 0x4d, 0x71, 0x07, 0x50, 0x93, 0x54,
	0xfc, 0x39, 0xb1, 0x0f, 0x78, 0x0d, 0x6b, 0x7f, 0x26, 0x9b, 0x1d, 0xb2, 0xe3, 0xae, 0x9a, 0x61,
	0x71, 0x02, 0x53, 0x93, 0x08, 0x8f, 0x88, 0xb0, 0xe9, 0xa9, 0xe3, 0xd8, 0x54, 0x8c, 0x37, 0xb0,
	0xe5, 0x8e, 0x2e, 0x1f, 0x76, 0xa5, 0xc5, 0x5f, 0x52, 0x3c, 0xc2, 0xae, 0x26, 0x79, 0x69, 0xde,
	0xf9, 0x2d, 0xcc, 0xb2, 0xf0, 0x35, 0x2c, 0xb2, 0x19, 0x27, 0x9b, 0xd5, 0x9f, 0xcd, 0x77, 0x06,
	0x7b, 0xcd, 0xe1, 0x07, 0xd7, 0x7b, 0x9d, 0x08, 0x24, 0x29, 0x48, 0x20, 0xc1, 0x5b, 0xc8, 0x7b,
	0xd7, 0xf2, 0xeb, 0xa5, 0x8d, 0x3a, 0x33, 0xd3, 0xe7, 0x16, 0x1f, 0xc0, 0x38, 0xb5, 0xb2, 0xeb,
	0x43, 0x76, 0xdc, 0x9f, 0xb0, 0x8c, 0xb7, 0x95, 0x4b, 0x88, 0x2a, 0x4e, 0x24, 0xe3, 0xcd, 0x62,
	0x8c, 0x16, 0xf2, 0x8e, 0xbd, 0x27, 0x61, 0xbb, 0xd5, 0x6a, 0xa2, 0x78, 0x0f, 0x26, 0xe8, 0xe5,
	0xd6, 0xe8, 0xde, 0xab, 0xff, 0x7b, 0x85, 0xc7, 0x2a, 0xb6, 0x1b, 0xa3, 0x2f, 0x7d, 0xfa, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x90, 0xd9, 0x7d, 0xe7, 0x60, 0x01, 0x00, 0x00,
}
